#  coding:utf-8

IMAGE_CODE_EXPIRES_SECONDS = 120  # 图片验证码有效期
SMS_CODE_EXPIRES_SECONDS = 300  # 短信验证码有效期

AREA_INFO_EXPIRES_SECONDS = 86400  # 区域信息缓存有效期

HOUSE_DETAIL_EXPIRES_SECONDS = 3600  # 房屋详情缓存有效期

HOUSE_LIST_PAGE_CAPACITY = 2  # 房屋默认每页展示量
HOUSE_LIST_REDIS_CACHED_PAGE = 2  # redis每次缓存房屋列表页数
HOUSE_LIST_REDIS_EXPIRES_SECONDS = 3600  # 房屋列表缓存时间   秒

HOME_PAGE_MAX_HOUSES = 4  # 首页展示的房子数
HOME_PAGE_DATA_REDIS_EXPIRE_SECOND = 3600  # 首页房屋缓存时间 秒